
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
#    volumes:
#      - "<YOUR-PATH-TO>/wordlist.json\
#        :/usr/src/app/public/data/simplified/wordlist.json\
#        :ro"

